import Head from 'next/head'
import Room from "../../components/Room";
import axios from "axios";
import {NEXT_API} from "../../config";
import Pagination from "../../components/Pagination";

export default function RoomsPage({rooms, total, page, RESULTS_PER_PAGE}) {

    return (
        <>
            <Head>
                <title>Sikal Homes</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Room rooms={rooms} />

            <Pagination page={page} total={total} perPage={RESULTS_PER_PAGE} />
        </>
    )
}

export const getServerSideProps = async (context) => {
    const {query: {page = 1}} = context;
    const {data} = await axios.get(`${NEXT_API}/api/rooms?page=${page}`);
    const total = data.roomsCount;
    const RESULTS_PER_PAGE = data.resultsPerPage;

    return {
        props: {
            rooms:data.rooms,
            page: +page,
            total,
            RESULTS_PER_PAGE
        }
    }
}